arb-dir: lib/l10n
template-arb-file: app_en.arb
output-class: SntoImUiLocalizations
output-dir: lib/generated/intl
synthetic-package: false
nullable-getter: false
use-deferred-loading: false
untranslated-messages-file: lib/generated/intl/untranslated_messages.txt
